// Canonical seed data for WapiLeo places (12 venues).
// Used by `prisma/seed.js`. The front-end keeps a trimmed copy as an offline
// fallback (see FALLBACK_PLACES in public/app.js) — keep the two in sync.

const U = (id) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;

export const PLACES = [
  { id: "warehouse", name: "Warehouse", area: "Masaki", price: "100k+", baseScore: 95, baseState: "Imeamka", line: "Late night, loud fits, Afrobeats, Amapiano, and zero sitting still.", image: U("1571266028243-d220c6a7edbf"), categories: ["all", "music"], tags: ["Amapiano", "Dress smart", "Late night"] },
  { id: "coral", name: "Coral Beach", area: "Masaki", price: "40k - 100k", baseScore: 91, baseState: "Moto sana", line: "Ocean air, cocktails, and date-night photos that do the talking.", image: U("1507525428034-b723cf961d3e"), categories: ["all", "date", "chill", "beach", "food"], tags: ["Great photos", "Date friendly", "Beach breeze"] },
  { id: "level8", name: "Level 8 Rooftop", area: "Kivukoni", price: "100k+", baseScore: 90, baseState: "Imeamka", line: "Rooftop sundowners, DJ sets, and the skyline doing its thing.", image: U("1516450360452-9312f5e86fc7"), categories: ["all", "music", "date", "chill"], tags: ["Rooftop", "Sundowners", "DJ sets"] },
  { id: "akemi", name: "Akemi Revolving Restaurant", area: "Upanga", price: "100k+", baseScore: 88, baseState: "Kuna vibe", line: "Dinner with a slow 360-degree view of the city lights.", image: U("1414235077428-338989a2e8c0"), categories: ["all", "date", "food", "chill"], tags: ["City views", "Fine dining", "Date friendly"] },
  { id: "samaki", name: "Samaki Samaki", area: "Mlimani City", price: "40k - 100k", baseScore: 87, baseState: "Kuna vibe", line: "Dinner, live music, and the table next to you probably knows the DJ.", image: U("1514933651103-005eec06c04b"), categories: ["all", "music", "food", "date"], tags: ["Live band", "Dinner", "Inajaa mapema"] },
  { id: "mamboz", name: "Mamboz Corner BBQ", area: "Kariakoo", price: "Under 40k", baseScore: 84, baseState: "Moto sana", line: "Legendary grilled mishkaki and the smoke that pulls a crowd.", image: U("1551218808-94e220e084d2"), categories: ["all", "food", "chill"], tags: ["Mishkaki", "Street food", "Budget friendly"] },
  { id: "slipway", name: "The Slipway", area: "Msasani", price: "40k - 100k", baseScore: 83, baseState: "Chill tu", line: "Sunset walk, dessert, calm talk, and a view that fixes the plan.", image: U("1519046904884-53103b34b206"), categories: ["all", "date", "chill", "beach", "food"], tags: ["Sunset", "Quiet-ish", "Walkable"] },
  { id: "kawe", name: "Kawe Beach", area: "Kawe", price: "40k - 100k", baseScore: 80, baseState: "Chill tu", line: "Wide sand, easy waves, and sunsets that end the week right.", image: U("1500530855697-b586d89ba3ee"), categories: ["all", "beach", "chill", "date"], tags: ["Beach day", "Sunset", "Relaxed"] },
  { id: "escape", name: "Escape One", area: "Mikocheni", price: "Under 40k", baseScore: 78, baseState: "Inajaa", line: "Games, light food, and an easy hangout when nobody wants pressure.", image: U("1511882150382-421056c89033"), categories: ["all", "games", "chill", "date"], tags: ["Games", "Low pressure", "Group plan"] },
  { id: "nyama", name: "Moyo Nyama", area: "Sinza", price: "Under 40k", baseScore: 76, baseState: "Kuna watu", line: "Nyama, football noise, and the kind of plan that becomes a story.", image: U("1544025162-d76694265947"), categories: ["all", "food", "chill"], tags: ["Budget friendly", "Football", "Nyama choma"] },
  { id: "mlimani-bowl", name: "Mlimani Bowling", area: "Mikocheni", price: "40k - 100k", baseScore: 73, baseState: "Inajaa", line: "Lanes, arcade noise, and an easy win for indecisive crews.", image: U("1492684223066-81342ee5ff30"), categories: ["all", "games", "chill"], tags: ["Bowling", "Arcade", "Group plan"] },
  { id: "george-dragon", name: "George & Dragon", area: "Masaki", price: "40k - 100k", baseScore: 71, baseState: "Kuna watu", line: "Pub pints, big-match nights, and a pool table with history.", image: U("1537633552985-df8429e8048b"), categories: ["all", "chill", "food", "games"], tags: ["Pub", "Sports", "Pool table"] },
];
